"""
Code templates for project generation.

Two rendering surfaces:

- :class:`Template` — render an inline string template (used by older
  templates that still live as Python string constants in this module).
- :class:`TemplateLoader` — load and render a ``.j2`` file shipped with the
  ``fastman`` package under ``_templates/``. Use this for new templates;
  it gets syntax highlighting, linter coverage, and supports
  ``{% include %}`` / ``{% extends %}`` between fragments.

Both surfaces use the same Jinja2 environment with autoescape OFF (we
generate Python source, not HTML) and ``StrictUndefined`` so a missing
context key fails loudly. Bare ``{`` / ``}`` characters pass through
unchanged — only ``{{ ... }}``, ``{% ... %}``, and ``{# ... #}`` are
interpreted.
"""
from typing import Any, Dict

from jinja2 import Environment, PackageLoader, StrictUndefined


# Shared environment for **inline** string templates — built once at import
# time, reused for every render. ``keep_trailing_newline=True`` preserves
# the final newline on generated files.
_jinja_env = Environment(
    autoescape=False,
    undefined=StrictUndefined,
    keep_trailing_newline=True,
    trim_blocks=False,
    lstrip_blocks=False,
)


# Environment for **file-backed** templates loaded from src/fastman/_templates/.
# Separate env (with its own PackageLoader) so ``{% include "x.j2" %}`` works
# inside .j2 files without leaking into inline rendering.
_jinja_file_env = Environment(
    loader=PackageLoader("fastman", "_templates"),
    autoescape=False,
    undefined=StrictUndefined,
    keep_trailing_newline=True,
    trim_blocks=False,
    lstrip_blocks=False,
)


class Template:
    """Jinja2-backed engine for inline string templates.

    Variable syntax is ``{{ name }}``. Conditionals and loops use
    ``{% if ... %}`` / ``{% for ... %}`` blocks — see the Jinja2 docs.
    """

    @staticmethod
    def render(template: str, context: Dict[str, Any]) -> str:
        """Render a template string with the given context."""
        return _jinja_env.from_string(template).render(**context)


class TemplateLoader:
    """Load and render ``.j2`` files shipped with the fastman package.

    Templates live under ``src/fastman/_templates/`` and are referenced by
    POSIX-style relative path (``"mail/base.py.j2"``). The loader is wired
    via ``jinja2.PackageLoader``, so packaging (``pip install fastman``)
    just works as long as ``_templates/**`` is included as package data.
    """

    @staticmethod
    def render(template_name: str, context: Dict[str, Any]) -> str:
        """Load ``_templates/<template_name>`` and render with `context`."""
        return _jinja_file_env.get_template(template_name).render(**context)


class Templates:
    """Repository of all code templates"""

    MAIN_APP = '''"""
{{ project_name }} - FastAPI Application
Generated by Fastman v{{ version }}
"""
from pathlib import Path
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from app.core.config import settings
from app.core.logging import setup_logging

# Setup logging
setup_logging()

# Initialize FastAPI
app = FastAPI(
    title=settings.PROJECT_NAME,
    version=settings.VERSION,
    docs_url=settings.DOCS_URL if settings.DEBUG else None,
    redoc_url=settings.REDOC_URL if settings.DEBUG else None,
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_HOSTS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount public directory for static files
if Path(settings.PUBLIC_DIR).is_dir():
    app.mount("/public", StaticFiles(directory=settings.PUBLIC_DIR), name="public")

# Health check
@app.get("/health")
def health_check():
    return {
        "status": "ok",
        "version": settings.VERSION,
        "environment": settings.ENVIRONMENT
    }

# Auto-discover and include routers
from app.core.discovery import discover_routers
discover_routers(app)

# GraphQL (optional)
try:
    from app.core.graphql import setup_graphql
    setup_graphql(app)
except ImportError:
    pass
'''

    CONFIG = '''"""Application configuration"""
import os
from pathlib import Path
from typing import List, Optional

from pydantic import computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict


def _get_env_file() -> str:
    """Resolve the environment file based on ENVIRONMENT variable.

    Supported values:
      - ``develop`` (default)  -> ``.env.develop``
      - ``staging``            -> ``.env.staging``
      - ``production``         -> ``.env`` (always — no ``.env.production`` exists;
                                 the bare ``.env`` is what the deployment platform
                                 populates from its secrets manager)

    Falls back to ``.env`` if the per-env file is missing.
    """
    env = os.getenv("ENVIRONMENT", "develop")
    if env == "production":
        return ".env"
    env_file = f".env.{env}"
    if Path(env_file).exists():
        return env_file
    return ".env"


class Settings(BaseSettings):
    """Application settings (Pydantic v2)."""

    model_config = SettingsConfigDict(
        env_file=_get_env_file(),
        case_sensitive=True,
        extra="ignore",
    )

    # Project
    PROJECT_NAME: str = "{{ project_name }}"
    VERSION: str = "1.0.0"
    ENVIRONMENT: str = "develop"
    DEBUG: bool = True

    # Security
    SECRET_KEY: str = "{{ secret_key }}"
    ALLOWED_HOSTS: List[str] = ["*"]

    {{ config_db_fields }}

    # API
    API_V1_PREFIX: str = "/api/v1"

    # Documentation
    DOCS_URL: Optional[str] = "/docs"
    REDOC_URL: Optional[str] = "/redoc"

    # Static files
    PUBLIC_DIR: str = "public"


settings = Settings()
'''

    DATABASE = '''"""Database configuration and session management (SQLAlchemy 2.0)."""
from typing import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import settings

# Create engine
engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if settings.DATABASE_URL.startswith("sqlite") else {},
    pool_pre_ping=True,
    echo=settings.DEBUG,
)

# Session factory
SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine,
)


class Base(DeclarativeBase):
    """Declarative base for all ORM models (SQLAlchemy 2.0 style)."""


def get_db() -> Generator[Session, None, None]:
    """Dependency for database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)
'''

    DATABASE_POSTGRESQL = '''"""PostgreSQL database (SQLAlchemy 2.0)."""
from typing import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import settings

# Create engine with PostgreSQL-specific settings
engine = create_engine(
    settings.database_url,
    pool_pre_ping=True,
    pool_size=10,
    max_overflow=20,
    pool_recycle=3600,
    echo=settings.DEBUG,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


def get_db() -> Generator[Session, None, None]:
    """Dependency for database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)
'''

    DATABASE_MYSQL = '''"""MySQL database (SQLAlchemy 2.0)."""
from typing import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import settings

engine = create_engine(
    settings.database_url,
    pool_pre_ping=True,
    pool_size=10,
    max_overflow=20,
    pool_recycle=3600,
    echo=settings.DEBUG,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


def get_db() -> Generator[Session, None, None]:
    """Dependency for database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)
'''

    DATABASE_ORACLE = '''"""Oracle database (SQLAlchemy 2.0)."""
from typing import Generator

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import settings

engine = create_engine(
    settings.database_url,
    pool_pre_ping=True,
    pool_size=10,
    max_overflow=20,
    pool_recycle=3600,
    echo=settings.DEBUG,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


def get_db() -> Generator[Session, None, None]:
    """Dependency for database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Initialize database tables"""
    Base.metadata.create_all(bind=engine)
'''

    DATABASE_FIREBASE = '''"""Firebase configuration and Firestore access"""
import firebase_admin
from firebase_admin import credentials, firestore
from typing import Optional
from app.core.config import settings
import logging

logger = logging.getLogger(__name__)

# Initialize Firebase Admin SDK
_db: Optional[firestore.Client] = None

def init_firebase():
    """Initialize Firebase Admin SDK"""
    global _db

    if _db is not None:
        return _db

    try:
        # Initialize with credentials
        cred = credentials.Certificate(settings.FIREBASE_CREDENTIALS_PATH)
        firebase_admin.initialize_app(cred, {
            'projectId': settings.FIREBASE_PROJECT_ID,
        })

        _db = firestore.client()
        logger.info("Firebase initialized successfully")
        return _db
    except Exception as e:
        logger.error(f"Failed to initialize Firebase: {e}")
        raise

def get_db() -> firestore.Client:
    """Get Firestore client instance"""
    global _db

    if _db is None:
        _db = init_firebase()

    return _db

# Collection helpers
class Collections:
    """Firestore collection names"""
    USERS = "users"
    # Add more collections as needed
'''

    LOGGING = '''"""Logging configuration"""
import logging
import sys
from pathlib import Path

def setup_logging(log_level: str = "INFO"):
    """Setup application logging"""

    # Create logs directory
    log_dir = Path("logs")
    log_dir.mkdir(exist_ok=True)

    # Configure logging
    logging.basicConfig(
        level=getattr(logging, log_level),
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(log_dir / "app.log")
        ]
    )

    # Set third-party loggers to WARNING
    logging.getLogger("uvicorn").setLevel(logging.WARNING)
    logging.getLogger("sqlalchemy").setLevel(logging.WARNING)
'''

    DISCOVERY = '''"""Auto-discovery of routers and features"""
import pkgutil
import importlib
from pathlib import Path
from fastapi import FastAPI, APIRouter
import logging

logger = logging.getLogger(__name__)

def discover_routers(app: FastAPI):
    """Discover and register all routers"""

    # Feature routers
    features_path = Path("app/features")
    if features_path.exists():
        for item in features_path.iterdir():
            if item.is_dir() and not item.name.startswith("_"):
                router_path = item / "router.py"
                if router_path.exists():
                    try:
                        module = importlib.import_module(f"app.features.{item.name}.router")
                        if hasattr(module, "router"):
                            app.include_router(module.router)
                            logger.info(f"Registered feature router: {item.name}")
                    except (ModuleNotFoundError, AttributeError) as e:
                        logger.error(f"Failed to load feature {item.name}: {e}")

    # API routers
    api_path = Path("app/api")
    if api_path.exists():
        for item in api_path.iterdir():
            if item.is_dir() and not item.name.startswith("_"):
                router_path = item / "router.py"
                if router_path.exists():
                    try:
                        module = importlib.import_module(f"app.api.{item.name}.router")
                        if hasattr(module, "router"):
                            app.include_router(module.router)
                            logger.info(f"Registered API router: {item.name}")
                    except (ModuleNotFoundError, AttributeError) as e:
                        logger.error(f"Failed to load API {item.name}: {e}")
'''

    GRAPHQL = '''"""GraphQL schema setup"""
import strawberry
from strawberry.fastapi import GraphQLRouter
from strawberry.tools import merge_types
from pathlib import Path
import importlib
import logging

logger = logging.getLogger(__name__)

def collect_schemas():
    """Collect all GraphQL queries and mutations"""
    queries = []
    mutations = []

    for path_name in ['features', 'api']:
        path = Path(f"app/{path_name}")
        if not path.exists():
            continue

        for item in path.iterdir():
            if not item.is_dir() or item.name.startswith("_"):
                continue

            schema_file = item / "schema.py"
            if not schema_file.exists():
                continue

            try:
                module = importlib.import_module(f"app.{path_name}.{item.name}.schema")
                if hasattr(module, "Query"):
                    queries.append(module.Query)
                if hasattr(module, "Mutation"):
                    mutations.append(module.Mutation)
            except (ModuleNotFoundError, AttributeError) as e:
                logger.error(f"Failed to load GraphQL schema from {item.name}: {e}")

    return queries, mutations

def setup_graphql(app):
    """Setup GraphQL endpoint"""
    queries, mutations = collect_schemas()

    # Default query if none found
    if not queries:
        @strawberry.type
        class Query:
            @strawberry.field
            def hello(self) -> str:
                return "Fastman GraphQL Ready"
        queries.append(Query)

    # Merge schemas
    ComboQuery = merge_types("Query", tuple(queries))
    ComboMutation = merge_types("Mutation", tuple(mutations)) if mutations else None

    schema = strawberry.Schema(
        query=ComboQuery,
        mutation=ComboMutation
    )

    graphql_app = GraphQLRouter(schema)
    app.include_router(graphql_app, prefix="/graphql")
    logger.info("GraphQL endpoint registered at /graphql")
'''

    ALEMBIC_ENV = '''"""Alembic environment configuration."""
import importlib
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the project root importable (alembic/env.py is at <project>/alembic/env.py
# so parents[1] is the project root).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.config import settings  # noqa: E402
from app.core.database import Base  # noqa: E402


def _import_all_models() -> None:
    """Import every model module so Base.metadata is populated.

    Alembic's autogenerate only sees what's already registered with
    Base.metadata at this point. Generated projects can place models in any
    of: app/models/, app/features/<x>/models.py, app/api/<x>/models.py.
    This walker imports them all so `alembic revision --autogenerate` picks
    up new tables without the user having to maintain a central import list.
    """
    project_root = Path(__file__).resolve().parents[1]
    candidates = []

    # Central models package
    models_pkg = project_root / "app" / "models"
    if models_pkg.is_dir():
        for f in sorted(models_pkg.glob("*.py")):
            if f.name == "__init__.py" or f.name.startswith("_"):
                continue
            candidates.append(f"app.models.{f.stem}")

    # Per-feature / per-API models
    for sub in ("features", "api"):
        base = project_root / "app" / sub
        if not base.is_dir():
            continue
        for child in sorted(base.iterdir()):
            if not child.is_dir() or child.name.startswith("_"):
                continue
            models_file = child / "models.py"
            if models_file.exists():
                candidates.append(f"app.{sub}.{child.name}.models")

    for module_path in candidates:
        try:
            importlib.import_module(module_path)
        except Exception as exc:  # pragma: no cover — best-effort discovery
            print(f"alembic: failed to import {module_path}: {exc}", file=sys.stderr)


_import_all_models()

config = context.config

# Resolve the database URL. For postgres/mysql/oracle, generated Settings
# expose a `database_url` computed property built from DB_HOST/USER/etc.
# For SQLite, only DATABASE_URL is set. Try the computed one first.
db_url = getattr(settings, "database_url", None) or settings.DATABASE_URL
if not db_url:
    raise RuntimeError(
        "Could not resolve a database URL from settings. "
        "Set DATABASE_URL or the DB_HOST/DB_USER/DB_PASSWORD trio."
    )
config.set_main_option("sqlalchemy.url", db_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

def run_migrations_offline():
    """Run migrations in 'offline' mode"""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()

def run_migrations_online():
    """Run migrations in 'online' mode"""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''

    ALEMBIC_INI = '''[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
'''

    ALEMBIC_SCRIPT_MAKO = '''"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''

    GITIGNORE = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
*.egg-info/
dist/
build/
*.egg

# Virtual Environment
.venv/
venv/
ENV/
env/

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~

# Environment
.env
.env.develop
.env.staging
.env.local
.env.*.local

# Database
*.db
*.sqlite
*.sqlite3

# Logs
logs/
*.log

# Testing
.pytest_cache/
.coverage
htmlcov/

# OS
.DS_Store
Thumbs.db

# Fastman
config_cache.json
.fastmanrc
'''
